version: '3.8'
services:
  postgres:
    image: postgres:18.1-alpine
    container_name: dreader-users
    environment:
      POSTGRES_DB: dreader_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: keycloak/keycloak:26.4.7
    ports:
      - 8180:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: dreader_users
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: adminpass
    networks:
      - keycloak-network
    depends_on:
      - postgres

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local