version: '3.8'
services:
  postgres:
    image: postgres:18-alpine
    container_name: dreader-news-parser
    environment:
      POSTGRES_DB: dreader_news_parser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: