ALTER TABLE post
    ADD COLUMN summary VARCHAR NOT NULL DEFAULT 'NULL';
ALTER TABLE post
    ADD COLUMN url VARCHAR(255) NOT NULL UNIQUE DEFAULT random();
ALTER TABLE post
    ADD COLUMN source_name VARCHAR(100) NOT NULL DEFAULT 'NULL';