spring:
  application:
    name: dreader-news
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dreader-micro, dreader-news, redis, kafka


threads:
  app-id: {THREADS_APP_ID}
  app-secret: {THREADS_APP_SECRET}
